name = "legalai-worker"
main = "worker.js"
compatibility_date = "2026-05-22"
compatibility_flags = ["nodejs_compat"]
keep_vars = true

[assets]
directory = "."
binding = "ASSETS"

[[kv_namespaces]]
binding = "OWNER_EVENTS_KV"
id = "21f0cd2f79114e85939ce4db969a79f6"

[[kv_namespaces]]
binding = "PAGOS_KV"
id = "fa7ab1df1ce94d9aa985fa7c6ab1ba86"

[[kv_namespaces]]
binding = "LEGALAI_TELEGRAM_KV"
id = "012e8109e76f42d9bdf1266bde2a01d5"

[secrets]
required = [
  "ADMIN_KEY",
  "CLAUDE_API_KEY",
  "EMAIL_TO",
  "EMAIL_FROM",
  "MERCADOPAGO_ACCESS_TOKEN",
  "MERCADOPAGO_PUBLIC_KEY",
  "OPENAI_API_KEY",
  "RESEND_API_KEY"
]
